trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: AzureCLI@2
    displayName: "Azure CLI"
    inputs:
      azureSubscription: "ARM (hirebarend)"
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: 'az group create -n nodb-function-app -l "West Europe"'
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "ARM Template deployment: Resource Group scope"
    inputs:
      azureResourceManagerConnection: "ARM (hirebarend)"
      subscriptionId: "2427e3e3-f607-4705-8318-55e1e2605405"
      resourceGroupName: "nodb-function-app"
      location: "West Europe"
      csmFile: "infrastructure-as-code/template.production.bicep"
      deploymentMode: Complete
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'
  - task: ArchiveFiles@2
    displayName: 'Archive $(System.DefaultWorkingDirectory)'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/artifact.zip'
  - task: AzureFunctionApp@2
    displayName: 'Azure Function App Deploy: func-nodb-prod-001'
    inputs:
      connectedServiceNameARM: 'ARM (hirebarend)'
      appType: functionAppLinux
      appName: 'func-nodb-prod-001'
      package: '$(Build.ArtifactStagingDirectory)/artifact.zip'
      runtimeStack: 'NODE|18'
